#config_version=5

  
hardware:
  platform: fast
  driverboards: fast

fast:
  ports: com20, com21
  
playfields:
  playfield:
    default_source_device: None
    tags: default
    
displays:
  window:
    width: 800
    height: 600
    
slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        
slide_player:
  init_done: welcome_slide
    
lights:
  l_left_outlane:
    start_channel: 0-0      # you could also use number: 0
    subtype: led
    type: grb
  l_left_inlane:
    previous: l_left_outlane
    subtype: led
    type: grb
  l_left_far_arrow:
    previous: l_left_inlane
    subtype: led
    type: grb
  l_left_far_square:
    previous: l_left_far_arrow
    subtype: led
    type: grb
  
  l_rectangle_1:
    previous: l_left_far_square
    subtype: led
    type: grb
  l_rectangle_2:
    previous: l_rectangle_1
    subtype: led
    type: grb
  l_rectangle_3:
    previous: l_rectangle_2
    subtype: led
    type: grb
  l_rectangle_4:
    previous: l_rectangle_3
    subtype: led
    type: grb
  
  l_left_inner_square:
    previous: l_rectangle_4
    subtype: led
    type: grb
  l_left_inner_arrow:
    previous: l_left_inner_square
    subtype: led
    type: grb
  
  l_drop_mid_left:
    previous: l_left_inner_arrow
    subtype: led
    type: grb
  l_drop_mid_mid:
    previous: l_drop_mid_left
    subtype: led
    type: grb
  l_drop_mid_right:
    previous: l_drop_mid_mid
    subtype: led
    type: grb
  
  l_middle_square:
    previous: l_drop_mid_right
    subtype: led
    type: grb
  l_middle_arrow:
    previous: l_middle_square
    subtype: led
    type: grb
  
  l_left_rollover:
    previous: l_middle_arrow
    subtype: led
    type: grb
  l_right_rollover:
    previous: l_left_rollover
    subtype: led
    type: grb
  
  l_right_inner_arrow:
    previous: l_right_rollover
    subtype: led
    type: grb
  l_right_inner_square:
    previous: l_right_inner_arrow
    subtype: led
    type: grb
  
  l_right_far_arrow:
    previous: l_right_inner_square
    subtype: led
    type: grb
  l_right_far_square:
    previous: l_right_far_arrow
    subtype: led
    type: grb
  
  l_drop_right_left:
    previous: l_right_far_square
    subtype: led
    type: grb
  l_drop_right_right:
    previous: l_drop_right_left
    subtype: led
    type: grb
  
  l_right_outlane:
    previous: l_drop_right_right
    subtype: led
    type: grb
  l_right_inlane:
    previous: l_right_outlane
    subtype: led
    type: grb
  
  l_wizard:
    previous: l_right_inlane
    subtype: led
    type: grb

  l_character_1_mode1:
    previous: l_wizard
    subtype: led
    type: grb
  l_character_1_mode2:
    previous: l_character_1_mode1
    subtype: led
    type: grb
  l_character_1_small3:
    previous: l_character_1_mode2
    subtype: led
    type: grb
  l_character_1_small2:
    previous: l_character_1_small3
    subtype: led
    type: grb
  l_character_1_small1:
    previous: l_character_1_small2
    subtype: led
    type: grb
  l_character_1_big:
    previous: l_character_1_small1
    subtype: led
    type: grb


  l_character_2_mode1:
    previous: l_character_1_big
    subtype: led
    type: grb
  l_character_2_mode2:
    previous: l_character_2_mode1
    subtype: led
    type: grb
  l_character_2_small3:
    previous: l_character_2_mode2
    subtype: led
    type: grb
  l_character_2_small2:
    previous: l_character_2_small3
    subtype: led
    type: grb
  l_character_2_big:
    previous: l_character_2_small2
    subtype: led
    type: grb
  l_character_2_small1:
    previous: l_character_2_big
    subtype: led
    type: grb
    
  l_character_3_big:
    previous: l_character_2_small1
    subtype: led
    type: grb
  l_character_3_small1:
    previous: l_character_3_big
    subtype: led
    type: grb
  l_character_3_small2:
    previous: l_character_3_small1
    subtype: led
    type: grb
  l_character_3_small3:
    previous: l_character_3_small2
    subtype: led
    type: grb
  l_character_3_mode2:
    previous: l_character_3_small3
    subtype: led
    type: grb
  l_character_3_mode1:
    previous: l_character_3_mode2
    subtype: led
    type: grb
    
  l_character_4_big:
    previous: l_character_3_mode1
    subtype: led
    type: grb
  l_character_4_mode1:
    previous: l_character_4_big
    subtype: led
    type: grb
  l_character_4_mode2:
    previous: l_character_4_mode1
    subtype: led
    type: grb
  l_character_4_small3:
    previous: l_character_4_mode2
    subtype: led
    type: grb
  l_character_4_small2:
    previous: l_character_4_small3
    subtype: led
    type: grb
  l_character_4_small1:
    previous: l_character_4_small2
    subtype: led
    type: grb

  l_2x:
    previous: l_character_4_small1
    subtype: led
    type: grb
  l_3x:
    previous: l_2x
    subtype: led
    type: grb
  l_4x:
    previous: l_3x
    subtype: led
    type: grb
  l_5x:
    previous: l_4x
    subtype: led
    type: grb





  
  

switches:

# Board 0 - Cabinet Board

  s_left_flipper:
    number: 0-4
    tags: left_flipper
  s_right_flipper:
    number: 0-0
    tags: right_flipper
  s_start:
    number: 0-2
    tags: start
  s_launch:
    number: 0-1
    tags:
    
# Board 1 - Backboard and Upper Mini Playfield

# Board 2 - Main

  s_pop_lower:
    number: 2-0
  s_pop_left:
    number: 2-1
  s_pop_right:
    number: 2-7
    
  s_drop_mid_right:
    number: 2-5
  s_drop_mid_mid:
    number: 2-4
  s_drop_mid_left:
    number: 2-3
    
  s_drop_right_right:
    number: 2-8
  s_drop_right_left:
    number: 2-9

  s_rollover_left:
    number: 2-13
    tags: playfield_active
  s_rollover_right:
    number: 2-6
    tags: playfield_active
    
  s_sling_left:
    number: 2-2
    
  s_vuk_back:
    number: 2-12
    type: 'NC'
  s_vuk_right:
    number: 2-11
    type: 'NC'
    
  s_drop_single:
    number: 2-10
  
# Board 3 - Lower Third
    
  s_trough_6:
    number: 3-8
    type: 'NC'
  s_trough_5:
    number: 3-9
    type: 'NC'
  s_trough_4:
    number: 3-10
    type: 'NC'
  s_trough_3:
    number: 3-11 
    type: 'NC'
  s_trough_2:
    number: 3-12
    type: 'NC'
    
  s_trough_1:
    number: 3-6
    type: 'NC'
  s_trough_jam:
    number: 3-5
    type: 'NC'
    
  s_autolauncher:
    number: 3-7
    
  s_eos_right:
    number: 3-4
    type: 'NC'
  s_eos_left:
    number: 3-3
    type: 'NC'
  s_eos_left_top:
    number: 3-0
    type: 'NC'
    
    
    
  s_right_outlane:
    number: 3-13
    tags: playfield_active
  s_right_inlane:
    number: 3-14
    tags: playfield_active
    
  s_left_outlane:
    number: 3-2
    tags: playfield_active
  s_left_inlane:
    number: 3-1  
    tags: playfield_active

  
    
# Board 4 - Sunken Mini

  s_bot_big:
    number: 4-3
    
  s_bot_left:
    number: 4-1
  s_bot_right:
    number: 4-2
    
  s_bot_back:
    number: 4-0
    
  s_bot_rollover:
    number: 4-4
    
  s_bot_vuk:
    number: 4-5
    
    
coils:

# Board 0 - Cabinet

# Board 1 - Backbox and Upper Mini

# Board 2 - Main

  c_pop_left:
    number: 2-4
  c_pop_right:
    number: 2-9
  c_pop_lower:
   number: 2-0
   
  c_top_vuk:
   number: 2-10
  c_right_vuk:
   number: 2-13
   
  c_drop_right:
   number: 2-14
  c_drop_right_left:
   number: 2-15
   default_pulse_power: 0.5


  c_drop_mid:
   number: 2-8
   default_pulse_ms: 50
   default_pulse_power: 0.7
  c_drop_mid_left:
   number: 2-5
   default_pulse_power: 0.5
  c_drop_mid_mid:
   number: 2-6
   default_pulse_power: 0.5
  c_drop_mid_right:
   number: 2-7
   default_pulse_power: 0.5

  c_drop_single:
   number: 2-11
  c_drop_single_knockdown:
   number: 2-12
   default_pulse_power: 0.25
   
  c_post_inlane:
   number: 2-1
   allow_enable: true
  c_post_outlane:
   number: 2-2
   allow_enable: true
   
  c_left_sling:
   number: 2-3
  
# Board 3 - Lower Third

  c_flipper_left:
    number: 3-5
    default_pulse_ms: 30
  c_flipper_left_hold:
    number: 3-4
    allow_enable: true
    default_hold_power: 1.0
    
  c_flipper_right:
    number: 3-3
    default_pulse_ms: 30
  c_flipper_right_hold:
    number: 3-2
    allow_enable: true
    default_hold_power: 1.0
    
  c_flipper_left_top:
    number: 3-7
    default_pulse_ms: 30
  c_flipper_left_top_hold:
    number: 3-6
    allow_enable: true
    default_hold_power: 1.0
    
  c_autolauncher:
    number: 3-0
    default_pulse_ms: 20
    default_pulse_power: 0.95
    
  c_trough:
    number: 3-1
    default_pulse_ms: 20
    default_pulse_power: 0.8




# Board 4 - Sunken Mini
        


drop_targets:
    d_drop_single:
      switch: s_drop_single
      reset_coil: c_drop_single
      knockdown_coil: c_drop_single_knockdown

    mid_right:
      switch: s_drop_mid_right
      reset_coil: c_drop_mid
    mid_mid:
      switch: s_drop_mid_mid
      reset_coil: c_drop_mid
    mid_left:
      switch: s_drop_mid_left
      reset_coil: c_drop_mid
      
    right_right:
      switch: s_drop_right_right
      reset_coil: c_drop_right
    right_left:
      switch: s_drop_right_left
      reset_coil: c_drop_right
      
drop_target_banks:
    mid:
      drop_targets:  mid_left, mid_right, mid_mid
      reset_coil: c_drop_mid
      reset_on_complete: 1s
     
    right:
      drop_targets: right_right, right_left
      reset_coil: c_drop_right
      reset_on_complete: 1s
      
autofire_coils:
    
  ac_lsling:
    coil: c_left_sling
    switch: s_sling_left
    
  ac_pop_lower:
    coil: c_pop_lower
    switch: s_pop_lower
  ac_pop_right:
    coil: c_pop_right
    switch: s_pop_right
  ac_pop_left:
    coil: c_pop_left
    switch: s_pop_left

