#config_version=5

  
hardware:
  platform: fast
  driverboards: fast

fast:
  ports: com14, com15
  rgb_buffer: 3
  
playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default
    
modes:
  - base
  - attract
  - tilt
  - lane_rotate
  
widget_styles:
  text_default:
    font_size: 21
    color: red
    
displays:
  window:
    width: 1280
    height: 390
    
window:
    width: 1280
    height: 390
    resizable: false
    fullscreen: true
    borderless: true
    source_display: window
    
slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL BY TPETCH
        color: green
        
slide_player:
  init_done: welcome_slide
    
lights:
  l_left_outlane:
    start_channel: 0-0     # you could also use number: 0
    subtype: led
    type: grb
  l_lower_entrance:
    previous: l_left_outlane
    subtype: led
    type: grb
  l_left_inlane:
    previous: l_lower_entrance
    subtype: led
    type: grb
  l_left_far_arrow:
    previous: l_left_inlane
    subtype: led
    type: grb
  l_left_far_square:
    previous: l_left_far_arrow
    subtype: led
    type: grb
  
  l_rectangle_1:
    previous: l_left_far_square
    subtype: led
    type: grb
  l_rectangle_2:
    previous: l_rectangle_1
    subtype: led
    type: grb
  l_rectangle_3:
    previous: l_rectangle_2
    subtype: led
    type: grb
  l_rectangle_4:
    previous: l_rectangle_3
    subtype: led
    type: grb
  
  l_left_inner_square:
    previous: l_rectangle_4
    subtype: led
    type: grb
  l_left_inner_arrow:
    previous: l_left_inner_square
    subtype: led
    type: grb
  
  l_drop_mid_left:
    previous: l_left_inner_arrow
    subtype: led
    type: grb
  l_drop_mid_mid:
    previous: l_drop_mid_left
    subtype: led
    type: grb
  l_drop_mid_right:
    previous: l_drop_mid_mid
    subtype: led
    type: grb
  
  l_middle_square:
    previous: l_drop_mid_right
    subtype: led
    type: grb
  l_middle_arrow:
    previous: l_middle_square
    subtype: led
    type: grb
  
  l_left_rollover:
    previous: l_middle_arrow
    subtype: led
    type: grb
  l_right_rollover:
    previous: l_left_rollover
    subtype: led
    type: grb
  
  l_right_inner_arrow:
    previous: l_right_rollover
    subtype: led
    type: grb
  l_right_inner_square:
    previous: l_right_inner_arrow
    subtype: led
    type: grb
  
  l_right_far_arrow:
    previous: l_right_inner_square
    subtype: led
    type: grb
  l_right_far_square:
    previous: l_right_far_arrow
    subtype: led
    type: grb
  
  l_drop_right_left:
    previous: l_right_far_square
    subtype: led
    type: grb
  l_drop_right_right:
    previous: l_drop_right_left
    subtype: led
    type: grb
  
  l_right_outlane:
    previous: l_drop_right_right
    subtype: led
    type: grb
  l_right_inlane:
    previous: l_right_outlane
    subtype: led
    type: grb
  
  l_wizard:
    previous: l_right_inlane
    subtype: led
    type: grb

  l_character_1_mode1:
    previous: l_wizard
    subtype: led
    type: grb
  l_character_1_mode2:
    previous: l_character_1_mode1
    subtype: led
    type: grb
  l_character_1_small3:
    previous: l_character_1_mode2
    subtype: led
    type: grb
  l_character_1_small2:
    previous: l_character_1_small3
    subtype: led
    type: grb
  l_character_1_small1:
    previous: l_character_1_small2
    subtype: led
    type: grb
  l_character_1_big:
    previous: l_character_1_small1
    subtype: led
    type: grb


  l_character_2_mode1:
    previous: l_character_1_big
    subtype: led
    type: grb
  l_character_2_mode2:
    previous: l_character_2_mode1
    subtype: led
    type: grb
  l_character_2_small3:
    previous: l_character_2_mode2
    subtype: led
    type: grb
  l_character_2_small2:
    previous: l_character_2_small3
    subtype: led
    type: grb
  l_character_2_big:
    previous: l_character_2_small2
    subtype: led
    type: grb
  l_character_2_small1:
    previous: l_character_2_big
    subtype: led
    type: grb
    
  l_character_3_big:
    previous: l_character_2_small1
    subtype: led
    type: grb
  l_character_3_small1:
    previous: l_character_3_big
    subtype: led
    type: grb
  l_character_3_small2:
    previous: l_character_3_small1
    subtype: led
    type: grb
  l_character_3_small3:
    previous: l_character_3_small2
    subtype: led
    type: grb
  l_character_3_mode2:
    previous: l_character_3_small3
    subtype: led
    type: grb
  l_character_3_mode1:
    previous: l_character_3_mode2
    subtype: led
    type: grb
    
  l_character_4_big:
    previous: l_character_3_mode1
    subtype: led
    type: grb
  l_character_4_mode1:
    previous: l_character_4_big
    subtype: led
    type: grb
  l_character_4_mode2:
    previous: l_character_4_mode1
    subtype: led
    type: grb
  l_character_4_small3:
    previous: l_character_4_mode2
    subtype: led
    type: grb
  l_character_4_small2:
    previous: l_character_4_small3
    subtype: led
    type: grb
  l_character_4_small1:
    previous: l_character_4_small2
    subtype: led
    type: grb

  l_2x:
    previous: l_character_4_small1
    subtype: led
    type: grb
  l_3x:
    previous: l_2x
    subtype: led
    type: grb
  l_4x:
    previous: l_3x
    subtype: led
    type: grb
  l_5x:
    previous: l_4x
    subtype: led
    type: grb
    

  l_shoot_again:
    number: 64      
    subtype: led
    type: grb
  l_lower_big:
    previous: l_shoot_again
    subtype: led
    type: grb
  l_lower_left:
    previous: l_lower_big
    subtype: led
    type: grb
  l_lower_right:
    previous: l_lower_left
    subtype: led
    type: grb
  l_lower_rollover:
    previous: l_lower_right
    subtype: led
    type: grb
  l_lower_back_circle:
    previous: l_lower_rollover
    subtype: led
    type: grb
  l_lower_back_square:
    previous: l_lower_back_circle
    subtype: led
    type: grb
  l_lower_exit:
    previous: l_lower_back_square
    subtype: led
    type: grb
    
  l_upper_exit:
    number: 128
    subtype: led
    type: grb
    
  l_upper_t:
    previous: l_upper_exit
    subtype: led
    type: grb
  l_upper_r:
    previous: l_upper_t
    subtype: led
    type: grb
  l_upper_a:
    previous: l_upper_r
    subtype: led
    type: grb
  l_upper_s:
    previous: l_upper_a
    subtype: led
    type: grb
  l_upper_h:
    previous: l_upper_s
    subtype: led
    type: grb
  l_upper_l:
    previous: l_upper_h
    subtype: led
    type: grb
  l_upper_a2:
    previous: l_upper_l
    subtype: led
    type: grb
  l_upper_n:
    previous: l_upper_a2
    subtype: led
    type: grb
  l_upper_d:
    previous: l_upper_n
    subtype: led
    type: grb
    
  l_upper_left_rollover:
    previous: l_upper_d
    subtype: led
    type: grb
  l_upper_middle_arrow:
    previous: l_upper_left_rollover
    subtype: led
    type: grb
  l_back_arrow:
    previous: l_upper_middle_arrow
    subtype: led
    type: grb
  l_back_target:
    previous: l_back_arrow
    subtype: led
    type: grb
  l_back_orbit_1:
    previous: l_back_target
    subtype: led
    type: grb
  l_back_orbit_2:
    previous: l_back_orbit_1
    subtype: led
    type: grb
  l_back_orbit_3:
    previous: l_back_orbit_2
    subtype: led
    type: grb
  l_back_orbit_4:
    previous: l_back_orbit_3
    subtype: led
    type: grb
  l_back_orbit_5:
    previous: l_back_orbit_4
    subtype: led
    type: grb
    
  
    





  
  

switches:

# Board 0 - Cabinet Board

  s_left_flipper:
    number: 0-4
    tags: left_flipper
  s_right_flipper:
    number: 0-0
    tags: right_flipper
  s_start:
    number: 0-2
    tags: start
  s_launch:
    number: 0-3
    tags:
    
  s_tilt:
    number: 0-5
    tags: tilt_warning
    
# Board 1 - Backboard and Upper Mini Playfield

  s_upper_rollover:
    number: 1-0
  s_drop_upper:
    number: 1-2
  s_upper_stationary:
    number: 1-1
    
  s_back_rollover:
    number: 1-11
  s_back_pop:
    number: 1-8
  s_back_stationary:
    number: 1-10
  
  
  s_transfer_rollover:
    number: 1-12
    
  s_left_orbit_prox:
    number: 1-13
    
  s_left_return:
    number: 1-7
    type: 'NC'
    

# Board 2 - Main

  s_pop_lower:
    number: 2-0
  s_pop_left:
    number: 2-1
  s_pop_right:
    number: 2-7
    
  s_drop_mid_right:
    number: 2-5
  s_drop_mid_mid:
    number: 2-4
  s_drop_mid_left:
    number: 2-3
    
  s_drop_right_right:
    number: 2-8
  s_drop_right_left:
    number: 2-9

  s_rollover_left:
    number: 2-13
    tags: playfield_active
  s_rollover_right:
    number: 2-6
    tags: playfield_active
    
  s_sling_left:
    number: 2-2
  s_sling_right:
    number: 2-15
    
  s_vuk_top:
    number: 2-12
    type: 'NC'

  s_vuk_right:
    number: 2-11
    type: 'NC'

    
  s_drop_single:
    number: 2-10
  
# Board 3 - Lower Third
    
  s_trough_6:
    number: 3-8
    type: 'NC'
  s_trough_5:
    number: 3-9
    type: 'NC'
  s_trough_4:
    number: 3-10
    type: 'NC'
  s_trough_3:
    number: 3-11 
    type: 'NC'
  s_trough_2:
    number: 3-12
    type: 'NC'
    
  s_trough_1:
    number: 3-16
    type: 'NC'
  s_trough_jam:
    number: 3-17
    type: 'NC'
    
  s_autolauncher:
    number: 3-7
    
  s_eos_right:
    number: 3-5
    type: 'NC'
  s_eos_left:
    number: 3-3
    type: 'NC'
  s_eos_left_top:
    number: 3-0
    type: 'NC'
    
    
    
  s_right_outlane:
    number: 3-13
    tags: playfield_active
  s_right_inlane:
    number: 3-14
    tags: playfield_active
    
  s_left_outlane:
    number: 3-2
    tags: playfield_active
  s_left_inlane:
    number: 3-1  
    tags: playfield_active

  
    
# Board 4 - Sunken Mini

  s_bot_big:
    number: 4-3
    
  s_bot_left:
    number: 4-7
  s_bot_right:
    number: 4-2
    
  s_bot_back:
    number: 4-0
    
  s_bot_rollover:
    number: 4-4
    
  s_bot_vuk:
    number: 4-5
    type: 'NC'

    
    
coils:

# Board 0 - Cabinet

  c_shaker:
    number: 0-0
    default_pulse_ms: 1
    default_hold_power: 0.125    # keep this low

# Board 1 - Backbox and Upper Mini

  c_back_flipper_main:
    number: 1-1
    default_pulse_ms: 40
  c_back_flipper_hold:
    number: 1-2
    allow_enable: true
    default_hold_power: 0.9
  c_back_pop:
    number: 1-0
    default_pulse_ms: 20
  c_flipper_upper:
    number: 1-5
    default_hold_power: 0.9
  c_drop_upper:
    number: 1-4
  c_drop_upper_knockdown:
    number: 1-3
    default_pulse_power: 0.25
    default_pulse_ms: 40

# Board 2 - Main

  c_pop_left:
    number: 2-4
  c_pop_right:
    number: 2-9
  c_pop_lower:
   number: 2-0
   
  c_top_vuk:
   number: 2-10
   default_pulse_ms: 200
   default_pulse_power: 1
  c_right_vuk:
   number: 2-13
   
  c_drop_right:
   number: 2-14
   default_pulse_ms: 60
   default_pulse_power: 0.7
  c_drop_right_left:
   number: 2-15
   default_pulse_power: 0.5


  c_drop_mid:
   number: 2-5
   default_pulse_ms: 50
   default_pulse_power: 0.7
  c_drop_mid_knockdown:
   number: 2-8
   default_pulse_power: 0.25
   default_pulse_ms: 40
   


  c_drop_single:
   number: 2-11
   default_pulse_ms: 50
   default_pulse_power: 0.9
  c_drop_single_knockdown:
   number: 2-12
   default_pulse_power: 0.25
   default_pulse_ms: 40
   
  c_post_inlane:
   number: 2-1
   allow_enable: true
  c_post_outlane:
   number: 2-2
   allow_enable: true
   
  c_left_sling:
   number: 2-3
  c_right_sling:
   number: 2-6
  
# Board 3 - Lower Third

  c_flipper_left:
    number: 3-4
    default_pulse_ms: 50
  c_flipper_left_hold:
    number: 3-5
    allow_enable: true
    default_hold_power: 0.9
    
  c_flipper_right:
    number: 3-2
    default_pulse_ms: 40
  c_flipper_right_hold:
    number: 3-3
    allow_enable: true
    default_hold_power: 0.9
    
  c_flipper_left_top:
    number: 3-6
    default_pulse_ms: 40
  c_flipper_left_top_hold:
    number: 3-7
    allow_enable: true
    default_hold_power: 0.9
    
  c_autolauncher:
    number: 3-0
    default_pulse_ms: 11
    default_pulse_power: 1
    
  c_trough:
    number: 3-1
    default_pulse_ms: 50
    default_pulse_power: 0.7




# Board 4 - Sunken Mini
        
        
  c_bot_top_flipper:
    number: 4-1
    allow_enable: true
    default_pulse_ms: 40
    default_hold_power: 0.9
  c_bot_bot_flipper:
    number: 4-3
    allow_enable: true
    default_pulse_ms: 20
  c_bot_bot_flipper_hold:
    number: 4-0
    allow_enable: true
    default_hold_power: 0.9
    
  c_bot_vuk:
    number: 4-2
    default_pulse_ms: 70
    default_pulse_power: 1



drop_targets:
    d_drop_single:
      switch: s_drop_single
      knockdown_coil: c_drop_single_knockdown
      knockdown_events: s_left_return_hit
      
    d_drop_upper:
      switch: s_drop_upper
      knockdown_coil: c_drop_upper_knockdown

      

    mid_right:
      switch: s_drop_mid_right

    mid_mid:
      switch: s_drop_mid_mid

    mid_left:
      switch: s_drop_mid_left

      
    right_right:
      switch: s_drop_right_right
      reset_coil: c_drop_right
      knockdown_events: balldevice_bd_right_vuk_ejecting_ball
    right_left:
      switch: s_drop_right_left

      
drop_target_banks:

    single_main:
      drop_targets: d_drop_single
      reset_coil: c_drop_single
      reset_events: 
        balldevice_bd_top_vuk_eject_success: 0.25s
        s_pop_right_hit: 0.25s
        ball_started: 0s
      reset_on_complete: 1s
      
    single_upper:
      drop_targets: d_drop_uppere
      reset_coil: c_drop_upper
      reset_events: ball_started

      
      
    mid:
      drop_targets:  mid_left, mid_right, mid_mid
      reset_coil: c_drop_mid
      reset_events: ball_started
      
     
    right:
      drop_targets: right_right, right_left
      reset_coil: c_drop_right
      reset_events: 
        balldevice_bd_right_vuk_eject_success: 1s
        ball_started: 0s
      
      
      
flippers:
  left_flipper:
    main_coil: c_flipper_left
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    
  left_top_flipper:
    main_coil: c_flipper_left_top
    hold_coil: c_flipper_left_top_hold
    activation_switch: s_left_flipper
    
  right_flipper:
    main_coil: c_flipper_right
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    
    
  bot_top_flipper:
    main_coil: c_bot_top_flipper
    activation_switch: s_left_flipper
  bot_bot_flipper:
    main_coil: c_bot_bot_flipper
    hold_coil: c_bot_bot_flipper_hold
    activation_switch: s_right_flipper
    
    
  upper_flipper:
    main_coil: c_flipper_upper
    activation_switch: s_left_flipper
    
    
  back_flipper:
    main_coil: c_back_flipper_main
    hold_coil: c_back_flipper_hold
    activation_switch: s_right_flipper
    
    

ball_devices:

  bd_trough:
    ball_switches: s_trough_1, s_trough_2, s_trough_3, s_trough_jam
    eject_coil: c_trough
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 25ms
    eject_targets: bd_plunger
    debug: true
    
  bd_plunger:
    ball_switches: s_autolauncher
    eject_coil: c_autolauncher
    player_controlled_eject_event: s_launch_active
    eject_targets: bd_top_vuk
    eject_timeouts: 2s

  bd_top_vuk:
    ball_switches: s_vuk_top
    eject_coil: c_top_vuk
    eject_timeouts: 2s
    
  bd_right_vuk:
    ball_switches: s_vuk_right
    eject_coil: c_right_vuk
    eject_timeouts: 2s
    
  bd_bot_vuk:
    ball_switches: s_bot_vuk
    eject_coil: c_bot_vuk
    eject_timeouts: 2s
      
autofire_coils:
    
  ac_lsling:
    coil: c_left_sling
    switch: s_sling_left
  ac_rsling:
    coil: c_right_sling
    switch: s_sling_right
    
    
    
  ac_pop_lower:
    coil: c_pop_lower
    switch: s_pop_lower
  ac_pop_right:
    coil: c_pop_right
    switch: s_pop_right
  ac_pop_left:
    coil: c_pop_left
    switch: s_pop_left
  ac_pop_back:
    coil: c_back_pop
    switch: s_back_pop

